name: CI
on: [push, pull_request]

jobs:
  build_test:
    name: Build and Test
    strategy:
      matrix:
        go: ['1.15', '1.16', '1.17']
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:2.4
        ports:
        - 9200:9200
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: actions/setup-go@v2.1.4
      with:
        go-version: ${{ matrix.go }}
        stable: false
    - uses: actions/cache@v3.0.10
      with:
        path: ~/go/pkg/mod
        key: ubuntu-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ubuntu-go-
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc git-core
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Install juju-db
      run: sudo snap install juju-db
    - name: Build and Test
      run: go test -mod readonly ./...
