audit-log-file: audit.log
mongo-url: localhost:27017
api-addr: localhost:8080
auth-username: admin
auth-password: example-passwd
#elasticsearch-addr: localhost:9200
# For locally running services.
#identity-public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
#identity-api-url: http://localhost:8081
# For production identity manager.
identity-public-key: o/yOqSNWncMo1GURWuez/dGR30TscmmuIxgjztpoHEY=
identity-api-url: https://api.jujucharms.com/identity
identity-location: https://api.jujucharms.com/identity/v1/discharger
# Agent credentials.
#agent-username: charmstore@admin@idm
#agent-key:
#  private: 85ZQqTnqiNdEggFVy7TGjRDGMulJHHz8UKkfVl5tTu8=
#  public: X3Yj/aThvG20FoBhRAIX+JbFk300r9Roc2D78r/37iw=
# Statistics Cache maximum age, default 1 hour
#stats-cache-max-age: 1h
#request-timeout: 500ms
#search-cache-max-age: 0s
# Uncomment to test with a terms service running locally
#terms-location: localhost:8085
access-log: /var/log/charmstore/access.log
provider-config:
    - type: jujublobstore
      mongo_addr: localhost:27017
      mongo_dbname: juju
      bucket_name: entitystore
      mode: read-write
# An example config using s3 and ceph:
#    - type: s3
#      bucket_name: charmstoretestbucket
#      disable_ssl: true
#      endpoint: http://10.0.5.117
#      key: O5W6PMIQZ83ODYCGVIGJ
#      secret: 6aqf5vyRONOvGFJkvH65xW7ttxZIKNZx0c2cPMTA
#      mode: read-write
# An example config using localfs. bucket_name is a relative or absolute directory name.
#    - type: localfs
#      bucket_name: localstore
#      mode: read-write
# An example config using s3 and a fake s3 server.
    #    - type: s3
    #  bucket_name: charmstoretestbucket
    #  disable_ssl: true
    #  endpoint: "192.168.15.197:8000"
    #  key: accessKey1
    #  region: us-east-1
    #  s3_force_path_style: true
    #  secret: verySecretKey1
