audit-log-file: audit.log
mongo-url: localhost:27017
api-addr: localhost:8080
auth-username: admin
auth-password: example-passwd
#elasticsearch-addr: localhost:9200
# For locally running services.
#identity-public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
#identity-api-url: http://localhost:8081
# For production identity manager.
identity-public-key: o/yOqSNWncMo1GURWuez/dGR30TscmmuIxgjztpoHEY=
identity-api-url: https://api.jujucharms.com/identity
identity-location: https://api.jujucharms.com/identity/v1/discharger
# Agent credentials.
#agent-username: charmstore@admin@idm
#agent-key:
#  private: 85ZQqTnqiNdEggFVy7TGjRDGMulJHHz8UKkfVl5tTu8=
#  public: X3Yj/aThvG20FoBhRAIX+JbFk300r9Roc2D78r/37iw=
# Statistics Cache maximum age, default 1 hour
#stats-cache-max-age: 1h
#request-timeout: 500ms
#search-cache-max-age: 0s
# Uncomment to test with a terms service running locally
#terms-location: localhost:8085
access-log: /var/log/charmstore/access.log
logging-level: <root>=DEBUG;mgo=INFO;bakery=INFO;httpbakery=INFO
